# Generated by Django 3.2.7 on 2021-11-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=60, verbose_name='English')),
                ('uzbek', models.CharField(max_length=60, verbose_name="O'zbekcha")),
            ],
        ),
        migrations.DeleteModel(
            name='Lugat',
        ),
    ]
